### PR TITLE
Pin dev dependency versions

### PR DESCRIPTION
**Pull request by jstasiak**
This will let us avoid mistakes with some of our dependencies
transparently updating and breaking our CI.

### CODE REVIEW

**Comment by jstasiak** [comment]
Ugh, that breaks PyPy CI

**Comment by davidparsson** [comment]
I've successfully used [pip-tools](https://github.com/jazzband/pip-tools) to create complete requirements files in other projects. Not sure if it's worth it here though, and the pypy problem would probably still be there?

**Comment by jstasiak** [comment]
Hmm, I think this should work if I manually modify the new file and limit black and mypy to be CPython-only – let me try

**Review by davidparsson — APPROVED** [review]
:shipit:

**Pull request merged**
